server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/_user
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    url: jdbc:postgresql://localhost:7000/_user
    password: postgres
    user: postgres
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 3
    consumer:
      group-id: 'user-microservice-group'
      bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      - name: user-command
    headers:
      command: 'command'

aws:
  region: 'eu-north-1'
  bucket:
    name: 'maks741.fastify'
  objects:
    name:
      separator: '/'
    suffix:
      audio: 'audio'
      thumbnail: 'thumbnail'