server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/music_download
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    url: jdbc:postgresql://localhost:7000/music_download
    user: postgres
    password: postgres

download:
  size:
    threshold:
      mb: 100
  out:
    path: '/home/maks/me/programming/pet/fastify/music-download/out/'
    format:
      audio: mp3
      thumbnail: png
  scripts:
    resource-path: '/script'
    validate: './youtube.vldt'
    download: './youtube.dwnld'

aws:
  region: 'eu-north-1'
  bucket:
    name: 'maks741.fastify'