server:
  port: 8060

download:
  timeout: 20000
  out:
    path: '/home/maks/me/programming/pet/fastify/music-download/out/'
    format:
      audio: mp3
      img: png
  script:
    run: './youtube.dwnld'
    resource:
      path: '/script'

aws:
  region: 'eu-north-1'