spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/auth
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    url: jdbc:postgresql://localhost:7000/auth
    password: postgres
    user: postgres