spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    url: jdbc:postgresql://localhost:7000/auth
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 3
    consumer:
      group-id: 'auth'
      bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
      enable-auto-commit: true
    producer:
      bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
      acks: 2
    topics:
      - name: 'user-command'
        partitions: 3
        replication-factor: 3

