spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    url: jdbc:postgresql://localhost:7000/auth
    user: postgres
    password: postgres
