server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: h2
    password: h2
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 3
    producer:
      bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: 'test-group-id'
      auto-offset-reset: earliest
    topics:
      - name: 'user-command'
        partitions: 3
        replication-factor: 3
    headers:
      command: 'command'

jwt:
  signing:
    key: 'super-secure-signing-key'

