spring:
  profiles:
    active: dev
  liquibase:
    enabled: true

jwt:
  signing:
    key: ${JWT_SIGNING_KEY}
  expiration:
    period: 21600000
  claims:
    user:
      id: 'userId'
      email: 'userEmail'
      role: 'userRole'