server:
  port: 8060
  address: 'localhost'

spring:
  datasource:
    url: jdbc:postgresql://localhost:7000/download
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    url: jdbc:postgresql://localhost:7000/download
    user: postgres
    password: postgres
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 3
    consumer:
      group-id: 'download-microservice-group'
      bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    topics:
      - name: 'user-command'
        partitions: 3
        replication-factor: 3
      - name: 'music-command'
        partitions: 3
        replication-factor: 3
    headers:
      command: 'command'

download:
  size:
    threshold:
      mb: 100
  out:
    path: '/home/maks/me/programming/pet/fastify/download/out/'
    format:
      audio: mp3
      thumbnail: png
  storage:
    path: '/home/maks/me/programming/pet/fastify/download/storage/'
  scripts:
    resource-path: '/script'
    validate: './youtube.vldt'
    download: './youtube.dwnld'

local:
  objects:
    suffix:
      audio: 'audio'
      thumbnail: 'thumbnail'